Components/NBrightBuyUtils.cs
I believe the resx values are returning empty strings so the null check won't work to allow for overriding the value with a string if a resx key is not found.
=> Mods to check the resx returns for empty string in addition to nulls.

App_LocalResources/General.ascx.fr-FR.resx, App_LocalResources/General.ascx.nl-NL.resx, App_LocalResources/General.ascx.resx, App_LocalResources/general.ascx.it-IT.resx
Order Details Process Order dropdown for Waiting & Being Manufactured are mismatched.  If you select Waiting the History shows Being Manufactured & vice versa.  I PR'd the default General resx but I can apply to the other languages if it's the right fix.  The other possibility is the ClassInfo.cs requires the fix..??
=> status 120 & 080

Components/PurchaseData.cs
I believe this prevents issues once the Type Code has been converted to ORDER
=> Defensive check to preserve the order status in the GUIDKey 

Themes/config/js/jquery.genxmlajax.js
This fix ensures number inputs (<input type="number">) have their genxml type set to "txt", which in turn saves to the xml when run through GenXml. Currently numbers (like postcodes) aren't being saved
=> Fix for number inputs not being serialised correctly

App_LocalResources/General.ascx.fr-FR.resx, App_LocalResources/General.ascx.nl-NL.resx, App_LocalResources/General.ascx.resx, App_LocalResources/general.ascx.it-IT.resx, Themes/config/default/Admin_ProductDetail.cshtml
This makes the label on the admin product detail page match the underlying id of the check box and describes it's function a little better.
=> Add DealerOnly resx 

Themes/config/js/admin_product.js
Should work to wake up the EditUrl Token so it can be used again in templates.  It was a casualty from the razor migration.
=> JS changes to support the EditUrl token.

Themes/Default/js/checkout.js
Next button clicks from the Billing and Shipping address checkout leave the Summary content partially off screen.  Js added to ensure the user views the order summary without having to scroll.
=> Ensure Checkout Order Summary is visible

Components/Categories/CategoryFunctions.cs
New properties are being entered with a non standard bool value that is lowercase.  It won't reflect properly in the details view unless you re-save the property.  Small chance this may be related to issue #57
=> Add new property default bool should be proper cased

Themes/ClassicAjax/Default/os_FrontOfficePageHeader.cshtml, Themes/Default/Default/Checkout_head.cshtml, Themes/Default/Default/FullCart_head.cshtml
This css isn't needed until a user is in the checkout process.  This should be a better place to load it.
=> Migrate Checkout CSS

Plugins/readme.txt
This readme is slightly wrong.  This will help users trying to delete a plugin.
=> Fix delete plugin example

Themes/ClassicAjax/Default/Search.cshtml, Themes/config/js/jquery.genxmlajax.js
Minor js change to allow passing data using the input type search.  It'll enable most browsers to clear the data from the input box without any additional code.
=> Add input type search support

Components/DataProvider.cs, Components/ItemLists/ListCount.cs, Components/NBrightBuyController.cs, Components/Product/ProductFunctions.cs, Components/SqlDataProvider/SqlDataProvider.cs, Installation/04.01.02.SqlDataProvider, Installation/Uninstall.SqlDataProvider, NBrightBuy.csproj, OpenStore.dnn
This will return the properties used in the filtering in the same sproc as the list count.  Initial approach was using the list view paged data and wasn't accurate.  The SQL and data provider code for that is still in place because it works however it's not being used by this PR.  Overall this reduces db activity & performs better especially if there is more complex filtering.  One could make the list count SQL dryer with more refactoring of the original sproc but it isn't critical.  Take a look at where the ListCount class is placed and make sure it's in it's proper place(thought about using  NBrightInfo).  It required adding a Using to it in NBrightBuyController so that also may be worth reviewing... I think it's alright but we can change it if you have a better approach.
=> Properties by products

Components/Cart/CartFunctions.cs
This makes the cart unique by user to prevent a user from logging on to the same PC resulting in seeing the last user's cart data.  It may also fix #36 though technically the cache key is already portal specific so the case scenario described you'll want to test again.
=> Make the cart user specific.

Components/NBrightBuyUtils.cs
The input param is being overridden by the Store settings.  There are a few usages of the RazorRender function that are passing the debugMode so this change would allow for those operate as expected.
=> Implement debugMode param for RazorRender

Themes/config/default/dashboard.html, Themes/config/default/dashordersbody.html
Links to order details from the dashboard to help make managing the orders easier.  It would be great to get the order detail page's return button to return back to the dashboard when a user arrives on an order detail via the dashboard.  Otherwise they end up going back to the main order list if they click the return button.  I don't think there is a token for the return tab id we can pass as the rtntab query param in the order details url?
=> Make dashboard orders link to details

Components/ItemLists/ItemListsFunctions.cs
The paramCmd generated by the button click to remove all lists isn't matching the server side switch case.  This fixes it on the server side and leaves product.js that creates the request as is.
=> Fixes item list delete paramCmd

App_LocalResources/General.ascx.resx, Components/Cart/CartData.cs, Providers/ShippingProvider/App_LocalResources/Shipping.ascx.resx, Providers/ShippingProvider/ShippingData.cs, Providers/ShippingProvider/ShippingProvider.cs, Providers/ShippingProvider/Themes/config/default/shippingheader.html, Themes/Default/Default/CheckoutTotals.cshtml
Added an option so shop owners can choose to calculating shipping on subtotal (original price) or calculating shipping on cart total value which already applies discount.
The shipping provider has a new checkbox for this use case and when activated the subtotal (original price) will be replace with subtotal (cart total value).
=> Added an option to calculate shipping on cart total value in place of subtotal (original price)

Themes/Default/Default/ItemList.cshtml, Themes/Default/js/product.js
I think this may be an option for addressing the remove list issue.  The main culprit was the missing hidden input. I altered the jquery that hides the html product lines since it was affecting all lists.  This limits the client side html elements being removed to the proper list.
=> Enable users to remove list

Components/ModSettings.cs
Add a defensive cache removal to the BuildSettingsDic func.
=> Ensure BuildSettingsDic cachekey gets removed

Components/PurchaseData.cs
Including the orders status check outside of the AddPurchaseDocs func lets us reduce PurchaseData SaveData xml property lookups and AddPurchasedDocs func calls.  I think this is a little more efficient especially in multi item cart purchases.
=> PurchaseData refactoring

Components/Cart/CartData.cs
If there are pathways that need to clear this cache key we should identify them but I think in most situations changes to the promo providers would/should involve a server cache clear anyhow.  The ValidateCart function gets called multiple times so leaning on cache should help a little bit here.
=> Add caching support for CartData ValidateCart promo providers.

Components/Cart/CartData.cs, Components/Cart/CartFunctions.cs
During the checkout address selection workflow the UpdateCartAddress function gets called 3 times synchronously so we can just do the ValidateCart call on the last ajax call and still ensure the shipping provider costs get applied to the PurchaseInfo.
=> Reduce CartData ValidateCart calls

Themes/ClassicAjax/Default/os_FrontOfficePageHeader.cshtml
I don't believe the list pop up ajax calls are required during checkout.  This template gets cached so I think the only option here is to add some js that will avoid calling the list popup during the checkout process.
=> Reduce loadItemListPopup func calls

Components/Product/ProductData.cs, Themes/Bootstrap4/Default/ProductDisplayDetail.cshtml, Themes/ClassicAjax/Default/ProductDisplayDetail.cshtml
This PR adds an overloads for GetRelatedProducts to use in razor scripts.
In stead of 
`var relatedProducts = product.GetRelatedProducts();`
which only gives you the products that have been registered as related, you can now also give an integer as a parameter:
`var relatedProducts = product.GetRelatedProducts(6);`
which will add products from the same categories your product is in, up the number you passed in.
=> improved related products

Components/GrpCatController.cs, Components/NBrightBuyController.cs, Components/Product/ProductData.cs, Components/Product/ProductUtils.cs, Providers/PromoProvider/PromoProvider.cs, Providers/PromoProvider/PromoUtils.cs
Changes to ensure the scheduler executes the MultiBuyPromoScheduler successfully for promotion pricing calculations.
Couple things worth noting.
I removing the unused usings from the PromoProvider.  We can re-introduce if it'll cause problems but I don't think it should. 
The GroupCatController change was also something that is not directly related to the portal id issue but I bumped into it en-route to testing that issue.  I received a null error which I added a defensive check to prevent.
All other changes are intended to ensure the portal id is available when GroupPromoScheduler DoWork func gets called by the scheduler.
Possible fix for the issue in discussion #185
=> Enhance portal id usage
