- Themes/Default/Default/OrderAdminList.cshtml
I think this would be the proper resx key to use to replace that hard coded string.
> Replace order number hard coded string with resx.

- Themes/ClassicAjax/Default/ProductDisplayAjax.cshtml
- Themes/ClassicAjax/Default/ProductDisplayAjaxList.cshtml
- Themes/ClassicAjax/Default/ProductDisplayAjaxList_paging.cshtml
- Themes/Default/js/product.js
- render/NBrightBuyRazorTokens.cs
Should fix Issue #26 and a couple other things.  We'll need to address the ajax category & filtering modules separately.
> multiple ajax product displays

- App_LocalResources/General.ascx.resx
In the BO when you change the status dd and save you can see these 2 status messages getting crossed in the audit log.
> Waiting & Being Manufactured strings are mismatched

- Admin/Import.ascx.cs
As discussed I disabled the call to the Validate method in the Import function.
> Validation disabled in the Import process

- Components/Address/AddressFunctions.cs
- Components/Categories/CategoryFunctions.cs
- Components/ItemLists/ItemListsFunctions.cs
- Components/Plugins/PluginFunctions.cs
- Components/Product/ProductFunctions.cs
- Components/Properties/PropertyFunctions.cs
I searched for any usages and only found this in the ClientFunctions class.  Should be safe to remove from the files submitted.
> Remove Components Func var

- Components/Product/ProductFunctions.cs
I think this belongs in the plugin security check.
> Migrate update boolean

- App_LocalResources/General.ascx.resx
Adds the BO fa cog spinner for en-US.
> Add BO processing icon for en-US

- Themes/Default/js/checkout.js
JS to enforce scrolling to top for all the checkout steps.   If it's better I can resubmit without the tabbing and white space changes.
> Scroll checkout to top

- Components/Plugins/PluginUtils.cs
This will clean up the xml file, the db entry for portal 99999 and clear the cache so the ui reflects changes.
> Plugin delete cleanup

- Themes/ClassicAjax/Default/ProductDisplayListBody.cshtml
- Themes/Default/js/product.js
No functional change but reduces the inline js that is generated when viewing a list of products.
> Optimize shopping list add remove js for product list view

- Themes/ClassicAjax/Default/ProductDisplayListBody.cshtml
- render/NBrightBuyRazorTokens.cs
This helps to avoid EntryUrl token instantiations of the NavigationData with the list view loop.  Some other minor changes to set vars outside of loop and minimize resx lookups.
> Product Display List Body Mods

- Themes/ClassicAjax/Default/ProductDisplayAjaxList.cshtml
- render/NBrightBuyRazorTokens.cs
More overloading to enable limiting NavigationData instantiations.
> Overload tokens with NavigationData

- Themes/ClassicAjax/Default/ProductDisplayDetail.cshtml
Change div to span to so that the css styling matches the list view.
> Product details OOS flag css

- Components/Product/ProductData.cs
Remove hard coded lang from ProductData Validate func.
> Remove hard coded lang

- Themes/config/js/admin_order.js
JS to enable loading specific orders from an eid in the path.
> Js to load order details

- Providers/ManualPaymentProvider/Themes/config/default/payment_ok.cshtml
- Themes/Default/Default/OrderAdmin_head.cshtml
Js to enable Order Admin page loads that send users/clients directly to an order detail rather than the full list.  Implemented in the manual payment provider.
>  Client order details

- Components/Cart/CartData.cs
- Components/Payments/PaymentFunctions.cs
- Payment.ascx.cs
I'm not seeing any usage of the boolean value returned.  Returning the OrderData would help reduce the resource consumption.
Fixes issue #84
> Make convert to order return order data.

- Components/Orders/OrderFunctions.cs
Removing the dashboard template cache when an order is saved to ensure dashboard reflects changes
> Refresh dashboard when  order is saved

- render/NBrightBuyRazorTokens.cs
Implements the ProductOptions token attributes param.
> Pass attributes param to ProductOption func.

- NBrightBuy.csproj
Remove CacheUtils from project.  This should have been removed with the other cache related PR.
> Remove CacheUtils from project

- Providers/TaxProvider/App_LocalResources/Tax.ascx.nl.resx
- Providers/TaxProvider/App_LocalResources/Tax.ascx.resx
- Providers/TaxProvider/TaxProvider.cs
- Providers/TaxProvider/Themes/config/default/settings.html
Changes to support tax calculations on discounted items.  Add support for enabling shipping tax.
> Discounted item & shipping taxes

- Providers/ShippingProvider/App_LocalResources/Shipping.ascx.resx
- Providers/ShippingProvider/Themes/config/default/shippingheader.html
- Providers/TaxProvider/App_LocalResources/Tax.ascx.fr-FR.resx
- Providers/TaxProvider/App_LocalResources/Tax.ascx.nl.resx
- Providers/TaxProvider/App_LocalResources/Tax.ascx.resx
- Providers/TaxProvider/TaxProvider.cs
- Providers/TaxProvider/Themes/config/default/settings.html
Adds support for shipping tax.  Implement a static ctor and members.  Fix tax exempt & free shipping limit resx misnomers.
> Shipping tax mods

- NBrightThumb.ashx.cs
Applies the thumbnail response content type fix as prescribed.  Fixes #112
> Set thumbnail handler image response content type

- NBrightThumb.ashx.cs
Prescribed cache improvement fix for #114
> Enhanced thumbnail caching

- Components/Clients/ClientData.cs
By altering our cache approach we can avoid the issue with the duplicate client data.  Fixes #115
> Enhance Clientdata caching

- Payment.ascx.cs
There should be no need to re-instantiate this OrderData since it's happening just a couple of lines earlier in the code flow.
> Reduce OrderData instantiations

- App_LocalResources/CartView.ascx.nl-NL.resx
- Themes/Bootstrap4/Default/MiniCart.cshtml
> bs4-minicart

- Themes/Bootstrap4/Default/Search.cshtml
> fix bs4 search

- Components/Orders/OrderFunctions.cs
Implement the returnLimit param.
> GetOrderListData return limit

- Components/Orders/OrderData.cs
> Repeat order flow changes

- Installation/Uninstall.SqlDataProvider
those were missing from the uninstall file
> dropped 2 sp's

- App_LocalResources/General.ascx.fr-FR.resx
- App_LocalResources/General.ascx.nl-NL.resx
- App_LocalResources/General.ascx.resx
- App_LocalResources/general.ascx.it-IT.resx
- Components/Categories/CategoryFunctions.cs
- Themes/config/default/Admin_Property.cshtml
- Themes/config/js/admin_property.js
JS alert for client side validation.  Stop server side processing if an invalid ref is found in the list.  Possible fix for #150
> Add property ref validation

- Themes/Bootstrap4/Default/ProductListAjaxFilter.cshtml
- Themes/Bootstrap4/js/product.js
- Themes/ClassicAjax/Default/ProductListAjaxFilter.cshtml
- Themes/Default/js/product.js
This PR makes the search in the ajaxfilterlist case insensitive.
> make search in filter list case insensitive

- Themes/config/default/dashboard.html
This PR fixes the link on the dashboard to an individual order.
> fixes link to order from dashboard

- Themes/Bootstrap4/Default/ProductDisplayAjaxList.cshtml
this PR fixes #175 so the sort dropdown works again in the Bootstrap4 Theme
> fix for #175

- Themes/config/js/jquery.genxmlajax.js
closes #178 by changing the check on length < 4 to a check for numeric characters only.
> fix for saving > 1000 items on properties list
